### ISSUE TITLE
403

### ISSUE THREAD

**Issue by Robertdecker12** [alexeyvasilyev/tinycam-api#1]
Failed to login.
Http failure response for http://192.168.1.76:8083/api/v1/login?user=rdecker@sc.rr.com&pwd=dylan4620: 403 Forbidden

**Comment by alexeyvasilyev-wyze** [comment]
I guess you need to make URL encode for params, check https://www.urlencoder.org/ for instance.
http://192.168.1.76:8083/api/v1/login?user=rdecker%40sc.rr.com&pwd=dylan4620

**Comment by Robertdecker12** [comment]
Not sure what you mean have you looked at the site

Kind of new at this any help would be great

Bob

**Comment by alexeyvasilyev** [comment]
You need to make URL encode for params, check https://www.urlencoder.org/ for instance.
Try this url
http://192.168.1.76:8083/api/v1/login?user=rdecker%40sc.rr.com&pwd=dylan4620

**Comment by Robertdecker12** [comment]
Where would I put the code

**Comment by Robertdecker12** [comment]
Tried stop not working

**Comment by Robertdecker12** [comment]
Camera are we on the app on the tablet but not the server

**Comment by Robertdecker12** [comment]
Still need help
